parameters:
    data_name: 'ihdp'
    model_name: 'aipw'
    config_name: 'ihdp_aipw'
    ate_method_list: ['naive','aipw']
    repetitions: 5
    seed: 4
    max_epochs: 100
    batch_size: 50
    lr: 0.001
    weight_decay: 0.05
    use_validation: False
    use_tensorboard: False
    alpha: [4,1,1]
