parameters:
    data_name: 'hcmnist'
    model_name: 'dragonnet'
    config_name: 'hcmnist_dragonnet'
    ate_method_list: ['naive']
    n_covariates: 0
    repetitions: 5
    seed: 13
    max_epochs: 100
    batch_size: 32
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.05
    use_validation: True
    use_validation_best: True
    use_dropout: False
    use_tensorboard: False
    source_size_p: 1
