parameters:
    data_name: 'ihdp'
    model_name: 'batle'
    config_name: 'ihdp_batle_02'
    ate_method_list: [ 'naive','aipw' ]
    repetitions: 10
    seed: 8
    max_epochs: 100
    batch_size: 250
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.08
    dropout_p: 0.5
    alpha: [3,4,1,0.5,4] #was 3,4
    use_validation: False
    use_dropout: True
    use_tensorboard: True
    use_source: True
    weight_1: 2
    source_size_p: 0.2
    forward_passes: 10