parameters:
    data_name: 'ihdp'
    model_name: 'batle'
    config_name: 'ihdp_batle_08'
    ate_method_list: [ 'naive','aipw' ]
    repetitions: 10
    seed: 8
    max_epochs: 100
    batch_size: 100
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.08
    dropout_p: 0.5
    alpha: [4, 4,0.5,0.25,4] # was 4, 4 , 1
    use_validation: False
    use_dropout: True
    use_tensorboard: True
    use_source: True
    weight_1: 4
    source_size_p: 0.8
    forward_passes: 10