parameters:
    data_name: 'gwas'
    model_name: 'batle'
    config_name: 'gwas_batle'
    ate_method_list: [ 'naive','aipw' ]
    repetitions: 5
    seed: 5
    max_epochs: 100
    batch_size: 250
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.05
    dropout_p: 0.5
    alpha: [5,2,1,1,4]
    use_validation: False
    use_dropout: True
    use_tensorboard: False
    use_source: True
    weight_1: 5