parameters:
    data_name: 'gwas'
    model_name: 'batle'
    config_name: 'gwas_batle_info'
    ate_method_list: ['naive']
    n_covariates: 10000
    n_sample: 2000
    repetitions: 5
    seed: 20
    max_epochs: 100
    batch_size: 250
    units1: 200
    units2: 100
    lr: 0.0001
    weight_decay: 0.001
    dropout_p: 0.25
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: True
    use_source: True
    forward_passes: 30
    informative_source: True