parameters:
    data_name: 'hcmnist'
    model_name: 'batle'
    config_name: 'hcmnist_batle'
    ate_method_list: [ 'naive','aipw' ]
    n_covariates: 0
    repetitions: 25
    seed: 4
    max_epochs: 100
    batch_size: 640
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.05
    dropout_p: 0.25
    alpha: [1, 1,0.5, 0.5,1, 0.5 ]
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: True
    use_source: True
    forward_passes: 30
    source_size_p: 1
    use_fix_digit: False
    source_size: 2000