parameters:
    data_name: 'ihdp'
    model_name: 'batle'
    config_name: 'ihdp_batle'
    ate_method_list: ['aipw','naive']
    repetitions: 30
    seed: 9
    max_epochs: 100
    batch_size: 250
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.08
    dropout_p: 0.25
    alpha: [2,4,0.01, 1,0.25,1]
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: False
    use_source: True
    forward_passes: 30