parameters:
    data_name: 'ihdp'
    model_name: 'batle'
    config_name: 'ihdp_batle_06'
    ate_method_list: [ 'naive','aipw' ]
    repetitions: 5
    seed: 5
    max_epochs: 100
    batch_size: 250
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.08
    dropout_p: 0.25
    alpha: [3,0.25,1,1,2]
    use_validation: False
    use_dropout: True
    use_tensorboard: False
    use_source: True
    weight_1: 2
    source_size_p: 0.6