parameters:
    data_name: 'ihdp'
    model_name: 'bdragonnet'
    config_name: 'ihdp_bdragonnet_aipw'
    ate_method_list: ['aipw']
    repetitions: 10
    seed: 8
    max_epochs: 100
    batch_size: 50
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.08
    dropout_p: 0.25
    alpha: [1,2,0]
    use_validation: False
    use_dropout: True
    use_tensorboard: False
    type_original: False