parameters:
    data_name: 'hcmnist'
    model_name: 'batle'
    config_name: 'hcmnist_batle_info_02_e'
    ate_method_list: ['naive']
    n_covariates: 0
    repetitions: 5
    seed: 5
    max_epochs: 100
    batch_size: 576
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.001
    dropout_p: 0.25
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: True
    use_source: True
    forward_passes: 30
    source_size_p: 1
    use_fix_digit: True
    source_size: 2000
    informative_source: True