parameters:
    data_name: 'ihdp'
    model_name: 'aipw'
    config_name: 'ihdp_aipw'
    ate_method_list: ['naive']
    repetitions: 5
    seed: 9
    max_epochs: 100
    batch_size: 50
    lr: 0.1
    weight_decay: 0.08
    use_validation: True
    use_validation_best: True
    use_tensorboard: False
