parameters:
    data_name: 'gwas'
    model_name: 'bdragonnet'
    config_name: 'gwas_bdragonnet'
    ate_method_list: ['naive','aipw']
    n_covariates: 10000
    n_sample: 2000
    repetitions: 25
    seed: 4
    max_epochs: 100
    batch_size: 100
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.05
    dropout_p: 0.25
    alpha: [1,1,1]
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: False
    type_original: False
    forward_passes: 30