parameters:
    data_name: 'ihdp'
    model_name: 'cevae'
    config_name: 'ihdp_cevae'
    ate_method_list: ['naive']
    repetitions: 5
    seed: 20
    max_epochs: 100
    batch_size: 50
    lr: 0.001
    weight_decay: 0.08
    use_validation: True
    use_validation_best: True
    use_dropout: False
    use_tensorboard: False