parameters:
    data_name: 'ihdp'
    model_name: 'dragonnet'
    config_name: 'ihdp_dragonnet'
    ate_method_list: ['naive']
    repetitions: 5
    seed: 9
    max_epochs: 100
    batch_size: 50
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.08
    use_validation: True
    use_validation_best: True
    use_dropout: False
    use_tensorboard: False