parameters:
    data_name: 'ihdp'
    model_name: 'bdragonnet'
    config_name: 'ihdp_bdragonnet_aipw'
    ate_method_list: ['aipw','naive']
    repetitions: 30
    seed: 9
    max_epochs: 100
    batch_size: 50
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.08
    dropout_p: 0.25
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: False
    type_original: False
    forward_passes: 30