parameters:
    data_name: 'hcmnist'
    model_name: 'bdragonnet'
    config_name: 'hcmnist_bdragonnet'
    ate_method_list: [ 'naive','aipw' ]
    n_covariates: 0
    repetitions: 25
    seed: 4
    max_epochs: 100
    batch_size: 128
    units1: 200
    units2: 100
    lr: 0.001
    weight_decay: 0.05
    dropout_p: 0.25
    use_validation: True
    use_validation_best: True
    use_dropout: True
    use_tensorboard: False
    forward_passes: 30
    type_original: False
    source_size_p: 1
    use_source_dig: True