parameters:
    data_name: 'ihdp'
    model_name: 'bdragonnet'
    config_name: 'ihdp_bdragonnet'
    ate_method_list: ['naive','aipw']
    repetitions: 10
    seed: 4
    max_epochs: 100
    batch_size: 50
    units1: 200
    units2: 100
    lr: 0.005
    weight_decay: 0.05
    dropout_p: 0.5
    alpha: [1,4,0]
    use_validation: False
    use_dropout: True
    use_tensorboard: False
    type_original: False